backend:
  name: github
  branch: master
  repo: daltn/gathering-growth

media_folder: 'static/img'
public_folder: '/img'

collections:
  - name: 'team'
    label: 'Team'
    folder: 'src/team'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'National Champion',
          name: 'nationalChampion',
          widget: 'string',
        }
      - { label: 'Common Name', name: 'commonName', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Year Crowned', name: 'crowned', widget: 'string' }
      - { label: 'Year Photographed', name: 'photographed', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
