backend:
  name: git-gateway
  branch: master

media_folder: 'static/img'
public_folder: '/img'

collections:
  - name: 'trees'
    label: 'Trees'
    folder: 'src/trees'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'National Champion', name: 'title', widget: 'string' }
      - { label: 'Common Name', name: 'common-name', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Year Crowned', name: 'crowned', widget: 'string' }
      - { label: 'Year Photographed', name: 'photographed', widget: 'string' }
      - { label: 'Circumference', name: 'circumference', widget: 'string' }
      - { label: 'Height', name: 'height', widget: 'string' }
      - { label: 'Avg Crown Spread', name: 'crown-spread', widget: 'string' }
      - { label: 'Total AF Points', name: 'total-af-points', widget: 'string' }
      - { label: Image-01, name: image-01, widget: image }
      - { label: Image-02, name: image-02, widget: image }
      - { label: Image-03, name: image-03, widget: image }
      - { label: Image-04, name: image-04, widget: image }
      - { label: 'Extra', name: 'extra', widget: 'markdown' }
