backend:
  name: git-gateway
  branch: master

media_folder: 'static/img'
public_folder: '/img'

collections:
  - name: 'trees'
    label: 'Trees'
    folder: 'src/posts'
    create: true
    slug: '{{fields.slug}}'
    fields:
      - { label: 'National Champion', name: 'title', widget: 'string' }
      - {
          label: 'Slug',
          name: 'slug',
          widget: string,
          hint: 'Give a unique URL slug for the page, no spaces only - allowed. If tree names overlap add 02 at the end. For example: acer-macrophyllum-02',
        }
      - { label: 'Date', name: 'date', widget: 'date', format: 'MM-DD-YYYY' }
      - { label: 'Common Name', name: 'common-name', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Year Crowned', name: 'crowned', widget: 'string' }
      - { label: 'Year Photographed', name: 'photographed', widget: 'string' }
      - {
          label: 'Circumference',
          name: 'circumference',
          widget: 'string',
          required: false,
        }
      - { label: 'Height', name: 'height', widget: 'string', required: false }
      - {
          label: 'Avg Crown Spread',
          name: 'crown-spread',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Total AF Points',
          name: 'total-af-points',
          widget: 'string',
          required: false,
        }
      - { label: Image-01, name: image-01, widget: image, required: false }
      - { label: Image-02, name: image-02, widget: image, required: false }
      - { label: Image-03, name: image-03, widget: image, required: false }
      - { label: Image-04, name: image-04, widget: image, required: false }
      - { label: 'Extra', name: 'extra', widget: 'markdown', required: false }
